services:
  postgres_primary:
    image: bitnami/postgresql:16
    container_name: postgres_primary
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgrespass
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
      POSTGRESQL_SYNCHRONOUS_COMMIT_MODE: on
      POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS: 2
    volumes:
      - pg_primary_data:/bitnami/postgresql
    networks:
      - dbnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_standby1:
    image: bitnami/postgresql:16
    container_name: postgres_standby1
    restart: unless-stopped
    depends_on:
      - postgres_primary
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgrespass
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: postgres_primary
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
    volumes:
      - pg_standby1_data:/bitnami/postgresql
    networks:
      - dbnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_standby2:
    image: bitnami/postgresql:16
    container_name: postgres_standby2
    restart: unless-stopped
    depends_on:
      - postgres_primary
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgrespass
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_MASTER_HOST: postgres_primary
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
    volumes:
      - pg_standby2_data:/bitnami/postgresql
    networks:
      - dbnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgpool:
    image: bitnami/pgpool:latest
    container_name: pgpool
    restart: unless-stopped
    depends_on:
      - postgres_primary
      - postgres_standby1
      - postgres_standby2
    environment:
      PGPOOL_BACKEND_NODES: 0:postgres_primary:5432,1:postgres_standby1:5432,2:postgres_standby2:5432
      PGPOOL_POSTGRES_USERNAME: postgres
      PGPOOL_POSTGRES_PASSWORD: postgrespass
      PGPOOL_SR_CHECK_USER: repl_user
      PGPOOL_SR_CHECK_PASSWORD: repl_pass
      PGPOOL_ADMIN_USERNAME: pgpool_admin
      PGPOOL_ADMIN_PASSWORD: pgpool_admin_pass
      PGPOOL_ENABLE_LOAD_BALANCING: "yes"
      PGPOOL_ENABLE_FAILOVER: "yes"
      PGPOOL_HEALTH_CHECK_PERIOD: 5
    volumes:
      - pgpool_config:/opt/bitnami/pgpool/conf
    ports:
      - "5433:5432" 
    networks:
      - dbnetwork
    healthcheck:
      test: ["CMD", "pgpool", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - dbnetwork
    environment:
       ADMINER_DEFAULT_SERVER: pgpool

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: postgresql://postgres:postgrespass@pgpool:5432/postgres?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - pgpool
    networks:
      - dbnetwork



networks:
  dbnetwork:

volumes:
  pg_primary_data:
  pg_standby1_data:
  pg_standby2_data:
  pgpool_config:
